- name: Enable both EPEL and Remi repositories
  yum: name={{ item }} update_cache=yes state=latest
  loop: [ 'epel-release', 'yum-utils' ]

- name: Install PHP Remi Repository
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm update_cache=yes state=latest
 
- name: Enable the PHP 7.3 Remi repository
  command: yum-config-manager --enable remi-php73
 
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"